### PR TITLE
send email on customer-created event on when has_account is true

### LINKED ISSUE #6: Prevent account registration email from being sent to guest users upon order creation
### Description:

I've noticed a problem with the customer.create event that triggers an account registration email. Specifically, when a user with the email test@test.com places an order as a guest, they receive an account registration email, even though they have not created an account. This becomes problematic when the same user decides to create an account at a later time (using the same email), as they will receive the same account registration email again, leading to a suboptimal user experience.

### Steps to reproduce:

1. As a guest user with email test@test.com, create an order.
2. Observe that an account registration email is sent to test@test.com.
3. As test@test.com, create a new account.
4. Observe that the same account registration email is sent to test@test.com again.

### Expected behavior:

The account registration email should only be triggered when customer.has_account is true. In the steps above, the email should not be sent at step 2, but should be sent at step 4.

### Suggested solution:

Modify the event trigger conditions for sending the account registration email to include a check for customer.has_account being true.

Please let me know if any additional information is required. Thank you!

### PR DESCRIPTION
**Pull request by tsvetann**
closes #6

### CODE REVIEW

**Comment by tsvetann** [comment]
@Hemann55 would you like to code review?

**Comment by Hemann55** [comment]
Merged. Thanks for adding tests

**Comment by tsvetann** [comment]
@Hemann55 thanks for merging. Can you please release the new npm version as I am unable to do so as it's your private registry. i will add more tests. Thanks

**Comment by Hemann55** [comment]
done 👍

**Pull request merged**
